version: '2.4'

services:
  video-miner-pool:
    image: videominer/transcoder
    container_name: video-miner-pool
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - "/etc/timezone:/etc/timezone:ro" # Set timezone to host timezone.
      - "/etc/localtime:/etc/localtime:ro" # Set time to host time.
    command:
      [
        "-ethAcctAddr",
        "<ETH_ADDRESS>",
        "-orchSecret",
        "<ORCH_SECRET>",
        "-maxSessions",
        "10",
      ]

networks:
  default:
    name: videominer-transcoder
